[KDE]
ShowDeleteCommand = false

[PreviewSettings]
EnableRemoteFolderThumbnail = false
MaximumRemoteSize = 0
MaximumSize = 15728640

[Icons]
Theme = Nordzy-dark

[Appearance]
Style = Fusion
ColorScheme = darker
